#**Section- 1**

In [ ]:
print("Iam Sushil")

Iam Sushil


Functions on Python

In [ ]:
def area_of_square(num):
  return num*num
print("The area  of first square is :",area_of_square(6))
print("The area of second square is:",area_of_square(5))

The area  of first square is : 36
The area of second square is: 25


In [ ]:

def area_of_circle(num):
  return 3.7*num
print("The area of Circle is:",area_of_circle(5))

The area of Circle is: 18.5


Lists in Python

In [ ]:
#creating a lists of fruits
fruits=["apple","banana","kiwi","orange","gava"]

#Acessing elements
# print(fruits[0])#acessing first element in the list
# print(fruits[4])#accessing the 5th element in the list
# print(fruits[-1])#accessing the last element in the  list
# print(fruits[-2])#accessing the 2nd  last element in the list

#Adding and removing elements from list
fruits.append("mango")
print(fruits)

#Removing elements from the list
fruits.remove("kiwi")
print(fruits)

['apple', 'banana', 'kiwi', 'orange', 'gava', 'mango']
['apple', 'banana', 'orange', 'gava', 'mango']


creating dictioneries

In [ ]:
student={
    "name":"Ram Sahi",
    "age":30,
    "course":"Computer Science"
}

#Accessing the value of particular key in dictionary
print(student["age"])

#Updating values of particular key in the dictioneary
student["age"]=60
print(student["age"])

#Adding the new key-value pair on the dictioneary
student["address"]="Kathmandu"
print(student)

#Removing a key-value pair from dictioneary

del student["course"]
print(student)


30
60
{'name': 'Ram Sahi', 'age': 60, 'course': 'Computer Science', 'address': 'Kathmandu'}
{'name': 'Ram Sahi', 'age': 60, 'address': 'Kathmandu'}


  **Temperature change**

In [ ]:
#Taking Input from the user
num =float(input("What is the temperature in celsius:"))
def todays_temp(num):
  return num*9/5+32
print("The temperature in Fahrenheit is:",todays_temp(num))



What is the temperature?:33
The temperature in Fahrenheit is: 91.4


**Age Calculator**

In [ ]:

import datetime
current_year = datetime.datetime.now().year
birth_year = int(input("Please enter your birth year in A.D. (e.g., 1995): "))
if birth_year > current_year:
    print("Error: Incorrect Birth Date please provide right input.")
else:
    age = current_year - birth_year
    print(f"You are {age} years old.")



Please enter your birth year in A.D. (e.g., 1995): 2030
Error: Incorrect Birth Date please provide right input.


**Simple Interest Calculator**

In [ ]:

principal = float(input("Enter the principal amount: "))
rate = float(input("Enter the annual rate of interest (%): "))
time = float(input("Enter the time in years: "))
simple_interest = (principal * rate * time) / 100
print(f"The simple interest is: {simple_interest:.2f}")


Enter the principal amount: 10
Enter the annual rate of interest (%): 5
Enter the time in years: 32
The simple interest is: 16.00


**BMI Calculator**

In [ ]:

weight = float(input("Enter your weight in kilograms (kg): "))
height = float(input("Enter your height in meters (m): "))
bmi = weight / (height ** 2)
if bmi < 18.5:
    category = "Underweight"
elif 18.5 <= bmi < 24.9:
    category = "Normal weight"
elif 25 <= bmi < 29.9:
    category = "Overweight"
else:
    category = "Obese"
print(f"Your BMI is: {bmi:.2f}")
print(f"You are categorized as: {category}")


Enter your weight in kilograms (kg): 70
Enter your height in meters (m): 1.8288
Your BMI is: 20.93
You are categorized as: Normal weight


**Currency Converter**


In [ ]:

exchange_rate = 136.87
amount_npr = float(input("Enter the amount in Nepali Rupees (NPR): "))
amount_usd = amount_npr / exchange_rate
print(f"{amount_npr:.2f} NPR is approximately {amount_usd:.2f} USD.")


Enter the amount in Nepali Rupees (NPR): 500000
500000.00 NPR is approximately 3653.10 USD.


In [ ]:
import random
print(random.randint(1,10))

4


#NUMPY BASICS


**CREATING A NUMPY ARRAY AND ITS ATTRIBUTES**

In [4]:
#importing numpy library
import numpy as np
#creating a list name "my_list"
my_list =[1,2,3,4,5,6,]
#creating a 1-D numpy array from "my_list"
my_arr =np.array(my_list)
#printing the array
print(my_arr)

#creating a 0-D array
arr_0d =np.array(43)
print(arr_0d)

#creating a 2-D array
arr_2d =np.array([[1,2,3],[4,5,6]])
print(arr_2d)

#creating a 3d-array
arr_3d =np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(arr_3d)


[1 2 3 4 5 6]
43
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


In [5]:
#creating array and its attributes
arr =np.array([[1,2,3,4],[5,6,7,8]])
print(arr)#printing the array
print(arr.shape)#printing the shape of array
print(arr.ndim)#dimensions
print(arr.dtype)#type
print(arr.size)#size

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
2
int64
8


#ACCESSING AND MANUPLATING THE  ARRAY ELEMENTS

In [7]:
#accessing the 1-D array elements
my_arr = np.array([2,3,4,5])
print(my_arr[2])

4


In [9]:
#accessing the 2-D array elements
my_arr = np.array([[2,3,4,5],[1,3,5,6]])
print(my_arr[1,3])

6


In [13]:
#accessing the 3-D array elements
my_arr = np.array([[[2,3,4,5],[1,3,5,6]],[[3,4,5,6],[5,6,7,8]]])
print(my_arr[0,1,2])

5


#NEGATIVE INDEXING

In [14]:
#accessing the 2-D array elements with negative indexing
my_arr = np.array([[2,3,4,5],[1,3,5,6]])
print(my_arr[1,-3])

3


#SLICING ARRAYS

### important concepts wile slicing array
###array[start:end]
###array[start:end:step]

In [15]:
arr = np.array([1,2,4,5,6,8,9,80,43])
print(arr[1:5])#slicing
print(arr[1:5:2])#slicing with step
print(arr[0:-1])#negative

[2 4 5 6]
[2 5]
[ 1  2  4  5  6  8  9 80]


In [16]:
#slicing a 2-D Numpy Array
arr = np.array([[1,2,3,4],[4,6,7,9]])
print(arr[1,1:-1])

#Homework :Experiment with slicing on a 3-D array


[6 7]


#CLASSWORK

In [18]:
#creating a Numpy array
import numpy as np
array_list=[7,14,21,28]
my_arr=np.array(array_list)
print(my_arr)

[ 7 14 21 28]


In [20]:
#creating 2-D array
arr_2d =np.array([[5,10,15],[20,25,30]])
print(arr_2d)

[[ 5 10 15]
 [20 25 30]]


In [23]:
#using np.zeros
zeros_arr = np.zeros((2, 3))
arange_arr = np.arange(0, 13, 3)
print("3. Zeros Array:\n", zeros_arr)
print("   Arange Array:", arange_arr)

3. Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]
   Arange Array: [ 0  3  6  9 12]


In [24]:
#creating numpy array
arr4 = np.array([2, 4, 6, 8])
result4 = arr4 * 3
print("4. Multiplied Array:", result4)

4. Multiplied Array: [ 6 12 18 24]


In [25]:
#numpy array slicing and indexing
arr5 = np.array([1, 3, 5, 7, 9, 11])
print("5. Third Element:", arr5[2])
print("   Slice (index 1 to 3):", arr5[1:4])

5. Third Element: 5
   Slice (index 1 to 3): [3 5 7]
